# -*- coding: utf-8 -*-
"""Kel 2 - Case study OOP with Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U39PNhAGD4DwsQkdW3lJhxLsFYoUu8QZ

Studi Independen - Modeling And Optimization Techniques In Data Warehousing Bootcamp 2023




Kelompok 2
*   Jiya Chairunisah
*   Dian Asri Yuliasari
*   Nona Rhizma Afriana
*   Novira Riski Herdian
*   Indira Maharani Hidayat

# Case study OOP with Python
Buatlah sebuah program untuk menghitung luas n bangun datar yang terdiri dari (Untuk nilai angka bebas):

1. Persegi
2. Persegi Panjang
3. Segitiga
4. Lingkaran (gunakan 3.14 untuk nilai pi)
5. Trapesium



Permintaan masukan harus disesuaikan dengan bangun datar yang akan dihitung luasnya, e.g. jika persegi, maka program hanya akan meminta satu masukan, i.e. sisi. Setelah didapatkan n luas bangun datar, urutkan luas bangun datar dari terkecil hingga terbesar dan hitung total luas bangun datar tersebut!

Buatlah penyelesaian kasus tersebut dalam paradigma pemrograman berorientasi objek!

Petunjuk: Anda perlu membuat kelas parent dengan nama BangunDatar. Kelas BangunDatar akan memiliki metode kosong bernama hitung luas().
"""

# masukkan class BangunDatar
class BangunDatar:
    def hitung_luas(self):
        pass

# Object berisi 5 luas bangun datar
class Persegi(BangunDatar):
    def __init__(self, sisi):
        self.sisi = sisi

    def hitung_luas(self):
        return self.sisi ** 2

class PersegiPanjang(BangunDatar):
    def __init__(self, panjang, lebar):
        self.panjang = panjang
        self.lebar = lebar

    def hitung_luas(self):
        return self.panjang * self.lebar

class Segitiga(BangunDatar):
    def __init__(self, alas, tinggi):
        self.alas = alas
        self.tinggi = tinggi

    def hitung_luas(self):
        return 0.5 * self.alas * self.tinggi

class Lingkaran(BangunDatar):
    def __init__(self, radius):
        self.radius = radius

    def hitung_luas(self):
        return 3.14 * self.radius * self.radius

class Trapesium(BangunDatar):
    def __init__(self, sisi_atas, sisi_bawah, tinggi):
        self.sisi_atas = sisi_atas
        self.sisi_bawah = sisi_bawah
        self.tinggi = tinggi

    def hitung_luas(self):
        return 0.5 * (self.sisi_atas + self.sisi_bawah) * self.tinggi

# Input jumlah bangun datar ingin dicari

n = int(input("Masukkan jumlah bangun datar: "))
bangun_datar_list = []

for i in range(n):
    print(f"Bangun datar ke-{i+1}:")
    jenis_bangun = input("Jenis bangun datar (persegi/persegi panjang/segitiga/lingkaran/trapesium): ").lower()

    if jenis_bangun == "persegi":
        sisi = float(input("Masukkan panjang sisi: "))
        bangun = Persegi(sisi)
    elif jenis_bangun == "persegi panjang":
        panjang = float(input("Masukkan panjang: "))
        lebar = float(input("Masukkan lebar: "))
        bangun = PersegiPanjang(panjang, lebar)
    elif jenis_bangun == "segitiga":
        alas = float(input("Masukkan panjang alas: "))
        tinggi = float(input("Masukkan tinggi: "))
        bangun = Segitiga(alas, tinggi)
    elif jenis_bangun == "lingkaran":
        radius = float(input("Masukkan radius: "))
        bangun = Lingkaran(radius)
    elif jenis_bangun == "trapesium":
        sisi_atas = float(input("Masukkan panjang sisi atas: "))
        sisi_bawah = float(input("Masukkan panjang sisi bawah: "))
        tinggi = float(input("Masukkan tinggi: "))
        bangun = Trapesium(sisi_atas, sisi_bawah, tinggi)
    else:
        print("Jenis bangun datar tidak valid.")
        continue

    bangun_datar_list.append(bangun)

# Menghitung luas bangun datar dan menyimpannya dalam list
luas_bangun_list = []
for bangun in bangun_datar_list:
    luas = bangun.hitung_luas()
    luas_bangun_list.append(luas)

# Mengurutkan luas bangun datar dari kecil ke besar
luas_bangun_list.sort()

# Menghitung total luas
total_luas = sum(luas_bangun_list)

# Menampilkan hasil
print("\nHasil Penghitungan:")
for i, bangun in enumerate(bangun_datar_list):
    print(f"Luas bangun datar ke-{i+1}: {luas_bangun_list[i]}")
print(f"Total luas bangun datar: {total_luas}")